### ISSUE TITLE
"There was some error!"

### ISSUE THREAD

**Issue by JeffreyCA** [hereisnaman/gitfame#28]
When trying [this query](https://gitfa.me/user/torvalds) I get "There was some error!"

**Comment by hereisnaman** [comment]
Consuming the github graphql api for fetching repo data, give error sometimes when there is a lot of data to be processed. I have already opened an issue in the github platform forum, regarding the issue. There is issue in their api, which break of timeout.

I'll try to explore more and will get back with the repo, which might have a large no. of commits,  of the user causing a timeout in the github api.

Thanks for reporting.

**Comment by hereisnaman** [comment]
so my bet is on linux. The application is handling the data correctly but there is issue with the github api.

**Comment by Lxxyx** [comment]
Same issue with username Lxxyx. Seems to be too many repo

**Comment by hereisnaman** [comment]
@JeffreyCA though the github api issue has not been resolved but I am able to manage performing analytics on linux too by requesting 1 repo data per round trip. The issue is resolved now.

@Lxxyx in your case it wasn't really the same issue but I missed having strict casing for the username field which is unique so it was working for Lxxyx but not lxxyx. I have resolved it. 

Thanks for reporting the errors. :)
